possibleQuestions = {
  "History":[ #Added by Cheska.
      {"Question":"In which year did the Berlin Wall fall, leading to the reunification of East and West Germany?",
        "Choices":["a) 1985", "b) 1989", "c) 1991", "d) 1993"],
       "Answer":"b"},
       {"Question":"What is considered the largest empire in history?",
        "Choices":["a) French Empire", "b) Qing Dynasty", "c) Roman Empire", "d) Mongol Empire"],
       "Answer":"d"},
      {"Question":"Which is the last dynasty in China?",
        "Choices":["a) Zhou Dynasty", "b) Shang Dynasty", "c) Qing Dynasty", "d) Han Dynasty"],
       "Answer":"c"},
      {"Question":"During which event was Korea separated into 2 nations?",
        "Choices":["a) World War II", "b) Korean Civil War", "c) Imjin War", "d) World War I"],
       "Answer":"a"},
      {"Question":"How old was Queen Elizabeth II when she was crowned the Queen of England?",
        "Choices":["a) 27", "b) 24", "c) 29", "d) 26"],
       "Answer":"a"},
      {"Question":"What was the name of the Ukrainian nuclear power plant that was the site of a nuclear disaster in April 1986?",
        "Choices":["a) Kharkiv", "b) Chernobyl", "c) Kyiv", "d) Rivne"],
       "Answer":"b"},
      {"Question":"Who was the first Emperor of Rome?",
        "Choices":["a) Julius Caesar", "b) Mark Anthony", "c) Gnaeus Pompeius Magnus", "d) Caesar Augustus"],
       "Answer":"d"},
      {"Question":"What is the world’s oldest recorded civilization?",
        "Choices":["a) Egypt", "b) Maya", "c) Mesopotamia", "d) Minoan"],
       "Answer":"c"},
      {"Question":"Which ancient figure is often considered the founder of Western philosophy?",
        "Choices":["a) Democritus", "b) Aristotle", "c) Socrates", "d) Plato"],
       "Answer":"c"},
      {"Question":"What was the global recession that lasted from 2007 to 2009 called?",
        "Choices":["a) The Great Depression", "b) The Great Recession", "c) The International Debt Crisis", "d) The East Asian Economic Crisis"],
       "Answer":"b"},
      {"Question":"What is the name of the whistleblower who leaked classified information from the National Security Agency (NSA) in 2013??",
        "Choices":["a) Edward Snowden", "b) Thomas Drake", "c) Jeffrey Sterling", "d) Chelsea Manning"],
       "Answer":"a"},
      {"Question":"In which year was John F. Kennedy assassinated?",
        "Choices":["a) 1955", "b) 1975", "c) 1953", "d) 1963"],
       "Answer":"d"},
      {"Question":"Who was the last Tsar of Russia?",
        "Choices":["a) Ivan the Terrible", "b) Vladimir Putin", "c) Nicholas II", "d) Anastasia Nikolaevna"],
       "Answer":"c"},
      {"Question":"Who won the 2008 U.S. Presidential election?",
        "Choices":["a) Barack Obama", "b) John Mcain", "c) George Bush", "d) Donald Trump"],
       "Answer":"a"},
      {"Question":"What year was the Paris Agreement signed?",
        "Choices":["a) 2015", "b) 1783", "c) 1947", "d) 1898"],
       "Answer":"a"},
      {"Question":"What U.S. government department was created in the wake of the September 11 attacks?",
        "Choices":["a) United States Department of Health and Human Services", "b) Administration for Children and Families", "c) The Department of Homeland Security", "d) United States Department of State"],
       "Answer":"c"},
      {"Question":"Which country in Asia was a significant member of the Axis in World War II?",
        "Choices":["a) Siam", "b) Japan", "c) China", "d) Mongolia"],
       "Answer":"b"},
      {"Question":"Who is the famous leader of Cuba who had 49 years in power?",
        "Choices":["a) Fidel Castro", "b) Che Guevara", "c) Simon Bolivar", "d) Andrés Manuel López Obrador"],
       "Answer":"a"},
      {"Question":"When did the Soviet Union cease to exist as a sovereign state?",
        "Choices":["a) 2000", "b) 1989", "c) 1996", "d) 1991"],
       "Answer":"d"},
      {"Question":"Who delivered the famous “I have a dream” speech",
        "Choices":["a) A. Philip Randolph", "b) Martin Luther King Jr.", "c) Roy Wilkins", "d) Whitney Young"],
       "Answer":"b"},
      ],
  "Science":[ #Assigned to Cheska.
      {"Question":"What branch of biology deals with the subject of insects?",
        "Choices":["a) Ornithology", "b) Botany", "c) Entomology", "d) Phycology"],
       "Answer":"c"},
      {"Question":"How many electrons are in sodium ion?",
        "Choices":["a) 8", "b) 10", "c) 12","d) 13"],
       "Answer":"b"},
      {"Question":"How old are the oldest fossils on earth?",
        "Choices":["a) 3.9 billion years old", "b) 5 billion years old", "c) 3.8 billion years old", "d) 2.8 billion years old"],
       "Answer":"a"},
      {"Question":"What is the region of space around a nucleus called where there is a very high probability of finding an electron?",
        "Choices":["a) Nuclear Envelope", "b) Nucleolus", "c) Orbital", "d) Nuclear Lamina"],
       "Answer":"c"},
      {"Question":"What element did Joseph Priestley discover in 1774?",
        "Choices":["a) Oxygen", "b) Chlorine", "c) Manganese", "d) Nitrogen"],
       "Answer":"a"},
      {"Question":"What is the nearest planet to the sun?",
        "Choices":["a) Mars", "b) Venus", "c) Mercury", "d) Neptune"],
       "Answer":"c"},
      {"Question":"How many elements are there in the periodic table?",
        "Choices":["a) 112", "b) 120", "c) 118", "d) 109"],
       "Answer":"c"},
      {"Question":"Optics is the study of what?",
        "Choices":["a) Light", "b) Magnification", "c) Texture", "d) Illusion"],
       "Answer":"a"},
      {"Question":"Dolly was the first-ever living creature to be cloned. What type of animal was she?",
        "Choices":["a) Monkey", "b) Mouse", "c) Dog", "d) Sheep"],
       "Answer":"d"},
      {"Question":"What part of the brain deals with hearing and language?",
        "Choices":["a) Parietal Lobe", "b) Temporal lobe", "c) Forebrain", "d) Hypothalamus"],
       "Answer":"b"},
      {"Question":"What is the symbol of the element silver?",
        "Choices":["a) Ag", "b) Au", "c) Si", "d) S"],
       "Answer":"a"},
      {"Question":"According to Apollo astronauts, the Moon smells like what?",
        "Choices":["a) Coal", "b) Burnt gunpowder", "c) Vacuum dust", "d) Smoke from a campfire"],
       "Answer":"b"},
      {"Question":"How do you calculate density?",
        "Choices":["a) Volume divided by mass", "b) Mass multiplied by the volume", "c) Volume plus weight", "d) Mass divided by volume"],
       "Answer":"d"},
      {"Question":"What is the name of the most recent supercontinent?",
        "Choices":["a) Gondwana", "b) Pannotia", "c) Zealandia", "d) Pangea"],
       "Answer":"d"},
      {"Question":"What is a unit that measures force?",
        "Choices":["a) Mach", "b) Newtons", "c) Kg", "d) Kelvin"],
       "Answer":"b"},
      {"Question":"What instrument do you use to measure wind speed?",
        "Choices":["a) Anemometer", "b) Barometer", "c) Macrometer", "d) Speedometer"],
       "Answer":"a"},
      {"Question":"What do you count on a tree to tell how old it is?",
        "Choices":["a) Height", "b) Branches", "c) Roots", "d) Rings"],
       "Answer":"d"},
      {"Question":"What does the gallbladder secrete?",
        "Choices":["a) Peritoneum", "b) Bile", "c) Hydrochloric acid", "d) Amniotic fluid"],
       "Answer":"b"},
      {"Question":"How many chambers make up the human heart?",
        "Choices":["a) 3", "b) 6", "c) 4", "d) 2"],
       "Answer":"c"},
      {"Question":"What is the first phase of mitosis?",
        "Choices":["a) Anaphase", "b) Conception", "c) Interphase", "d) Prophase"],
       "Answer":"c"},
      ],
  "Business":[ #Assigned to Cheska.
      {"Question":"Mr. Jones sold two pipes at $1.20 each. Based on the cost, his profit one was 20% and his loss on the other was 20%. On the sale of the pipes, he:",
        "Choices":["a) Broke even", "b) Lost 10 cents", "c) Gained 4 cents", "d) Lost 4 cents"],
       "Answer":"b"},
      {"Question":"A potential investor is seeking to analyze the current economy. She is interested in a measure of GDP represented in current dollars. What GDP value will she MOST likely utilize?",
        "Choices":["a) Real GDP", "b) Nominal GDP", "c) Long-term capital gains", "d) Short-term capital gains"],
       "Answer":"b"},
      {"Question":"Swarovski is associated with what product?",
        "Choices":["a) Luxury watches", "b) Haute Couture clothing", "c) Crystal Jewelry", "d) High-end accessories"],
       "Answer":"c"},
      {"Question":"The company behind Facebook recently changed their name - what did they change it to?",
        "Choices":["a) Infini", "b) Delta", "c) Alpha", "d) Meta"],
       "Answer":"d"},
      {"Question":"Which of the following indicators is influenced by GDP (Gross Domestic Product)?",
        "Choices":["a) Age", "b) Literacy rate", "c) Price", "d) Supply"],
       "Answer":"b"},
      {"Question":"In economics, it is all about what?",
        "Choices":["a) Supply of free market goods", "b) Demand for the government to stop being corrupt", "c) Abundance of money and the choices we make", "d) Scarcity of resources and the choices we make"],
       "Answer":"d"},
      {"Question":"According to the Law of Supply, as price goes _____, supply goes ______.",
        "Choices":["a) Up, up", "b) Up, down", "c) Down, down", "d) Up, nowhere"],
       "Answer":"a"},
      {"Question":"Which is not one of the five classifications of accounts?",
        "Choices":["a) Sales", "b) Expenses", "c) Assets", "d) Liabilities"],
       "Answer":"a"},
      {"Question":"Which of the following is an example of an asset?",
        "Choices":["a) Prepaid expenses", "b) Notes payable", "c) Service revenue", "d) Withdrawals"],
       "Answer":"a"},
      {"Question":"Jane sells biscuits to a shop. The shop pays her $0.80 per biscuit. If Jane makes 42 biscuits in one week, how much does she earn?",
        "Choices":["a) $32.00", "b) $36.30", "c) $33.60", "d) $35.30"],
       "Answer":"c"},
      {"Question":"Find the percentage profit on an iPad purchased for $320 and later sold for $459.",
        "Choices":["a) 43.4%", "b) 44.3%", "c) 44.7%", "d) 34.4%"],
       "Answer":"a"},
      {"Question":"Express $1278.30 per fortnight as an annual salary.",
        "Choices":["a) $33,235.80", "b) $30,679.20", "c) $15,339.60", "d) $66,471.60"],
       "Answer":"a"},
      {"Question":"A 5% discount is applied to a mobile phone bill, which was $64.50. How much is the bill now?",
        "Choices":["a) $62.80", "b) $60.82", "c) $59.50", "d) $61.28"],
       "Answer":"d"},
      {"Question":"Calculate the monthly installment needed to repay a loan of $15,800 over 36 months at 6% pa.",
        "Choices":["a) $438.89", "b) $284.40", "c) $517.89", "d) $539.80"],
       "Answer":"c"},
      {"Question":"Which of these is neither a good nor a service?",
        "Choices":["a) A gallon of gasoline", "b) A piano lesson", "c) A meal at a restaurant", "d) A $20 bill"],
       "Answer":"d"},
      {"Question":"What is Gross Domestic Product (GDP)?",
        "Choices":["a) The total value of goods and services produced in a country.", "b) The total number of maids in a country.", "c) The amount of a person’s paycheck.", "d) The total number of goods produced in a country."],
       "Answer":"a"},
      {"Question":"In a market, where are economic decisions made?",
        "Choices":["a) By the producer", "b) By the consumer", "c) In the government", "d) In the market place"],
       "Answer":"d"},
      {"Question":"Jeff Bezos is the founder of which billion-dollar company?",
        "Choices":["a) Youtube", "b) Tesla", "c) Amazon", "d) Apple"],
       "Answer":"c"},
      {"Question":"What does the 'C' in CEO stand for?",
        "Choices":["a) Captain", "b) Corporate", "c) Company", "d) Chief"],
       "Answer":"d"},
      {"Question":"Which of the following is an American e-commerce company focused on handmade or vintage items?",
        "Choices":["a) Ali Express", "b) Amazon", "c) Ebay", "d) Etsy"],
       "Answer":"c"},
      ],
    "Pop Culture":[ #Assigned to Cheska.
      {"Question":"In the classic '90s sitcom 'Friends,' which character famously shouted 'We were on a break!' during a heated argument with their significant other?",
        "Choices":["a) Ross", "b) Rachel", "c) Chandler", "d) Monica"],
       "Answer":"a"},
      {"Question":"In the world of film, who directed the 1979 science fiction horror classic 'Alien'?",
        "Choices":["a) Steven Spielberg", "b) Ridley Scott", "c) James Cameron", "d) George Lucas"],
       "Answer":"b"},
      {"Question":"In the 'Harry Potter' book series, which Hogwarts House did Luna Lovegood belong to?",
        "Choices":["a) Gryffindor", "b) Hufflepuff", "c) Ravenclaw", "d) Slytherin"],
       "Answer":"c"},
      {"Question":'In the TV series "Stranger Things," what is the name of the parallel dimension inhabited by the Demogorgon and other creatures?',
        "Choices":["a) The Abyss", "b) The Netherworld", "c) The Shadow Realm", "d) The Upside Down"],
       "Answer":"d"},
      {"Question":"In the film 'The Godfather,' there's a memorable line: 'I'm gonna make him an offer he can't refuse.' Who says this iconic line?",
        "Choices":["a) Michael Corleone", "b) Vito Corleone", "c) Fredo Corleone","d) Sonny Corleone"],
       "Answer":"b"},
      {"Question": 'In the movie "Mean Girls," what is the name of the high school attended by the main characters, where most of the drama and comedy takes place?',
       "Choices": ["a) North Shore High School", "b) Eastwood High School", "c) Westfield High School", "d) Southside High School"],
       "Answer": "a"},
      {"Question": 'Which iconic American motorcycle manufacturer, founded in 1903, is known for its heavyweight motorcycles and signature V-twin engines?',
       "Choices": ["a) Harley-Davidson", "b) Indian Motorcycle", "c) Triumph", "d) Ducati"],
       "Answer": "a"},
      {"Question":'Which Swiss watchmaker, founded in 1833, is renowned for its complicated and innovative timepieces, including the Royal Oak and Royal Oak Offshore collections?',
        "Choices":["a) Patek Philippe", "b) Audemars Piguet", "c) Vacheron Constantin", "d) Breguet"],
       "Answer":"b"},
      {"Question":"This high-end Italian automaker, founded in 1914, is known for its prancing horse logo and produces some of the world's most coveted sports cars. Which brand is it?",
        "Choices":["a) Lamborghini", "b) Maserati", "c) Ferrari", "d) Alfa Romeo"],
       "Answer":"c"},
      {"Question":'Who directed the 1994 film "Pulp Fiction" which is known for its non-linear narrative and iconic characters?',
        "Choices":["a) Martin Scorsese", "b) Quentin Tarantino", "c) Steven Spielberg", "d) Christopher Nolan"],
       "Answer":"b"},
      {"Question":"Who is the protagonist of “Nineteen Eighty-Four”?",
        "Choices":["a) Winston Smith", "b) Cedric Smyth", "c) Seth Winston", "d) Walter Winston"],
       "Answer":"a"},
      {"Question":"In “The Great Gatsby”, what is the name of Nick Carraway’s cousin, who also happens to be the object of Jay Gatsby’s affection?",
        "Choices":["a) Lilian Gatz", "b) Jordan Baker", "c) Daisy Buchanan", "d) Myrtle Wilson"],
       "Answer":"c"},
      {"Question":"What year was the first iPhone released?",
        "Choices":["a) 2000", "b) 2006", "c) 2007", "d) 2009"],
       "Answer":"c"},
      {"Question":"Who became the most decorated gymnast in history during the 2010s?",
        "Choices":["a) Aly Raisman", "b) Simone Biles", "c) Olga Korbut", "d) Shannon Miller"],
       "Answer":"b"},
      {"Question":"Which country hosted the 2016 Olympics?",
        "Choices":["a) Greece", "b) USA", "c) Brazil", "d) Japan"],
       "Answer":"c"},
      {"Question":"Which comedian did Will Smith infamously slap at the 2022 Academy Awards?",
        "Choices":["a) Barry Jenkins", "b) James Franco", "c) Bradley Cooper", "d) Chris Rock"],
       "Answer":"d"},
      {"Question":"What modern-day item made a cameo in the final season of Game of Thrones?",
        "Choices":["a) Starbucks cup", "b) Umbrella", "c) Hair clip", "d) iPhone"],
       "Answer":"a"},
      {"Question":"What's the name of the dwarf who accompanies Frodo on his quest in the Lord of the Rings films?",
        "Choices":["a) Gollum", "b) Samwise", "c) Gimli", "d) Bilbo"],
       "Answer":"c"},
      {"Question":"Who is the highest-grossing movie star of all time?",
        "Choices":["a) Angelina Jolie", "b) Harrison Ford", "c) Robert Downey Jr.", "d) Morgan Freeman"],
       "Answer":"b"},
      {"Question":"Kaia Gerber is the daughter of what famous supermodel?",
        "Choices":["a) Kate Upton", "b) Cindy Crawford", "c) Gisele Bündchen", "d) Kate Moss"],
       "Answer":"b"},
      {"Question":"What is the name of the fictional paper company that Michael Scott works at on the show “The Office”?",
        "Choices":["a) Wernham Hogg Paper", "b) Reynholm Industries’ Basement", "c) Dunder Mifflin", "d) York Paper"],
       "Answer":"c"},
      ]}